version: '3'

services:
  reverse-proxy:
    image: traefik:v2.3
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  service1:
    build: ./services1
    labels:
      - "traefik.http.routers.whoami.rule=Host(`service1.docker.localhost`) || ( Host(`localhost`) && PathPrefix(`/s1`) )"