version: '3'

services:
  reverse-proxy:
    image: traefik:v2.3
    command: --api.insecure=true --providers.docker
    ports:
      #port -> main interface
      - "80:80"
      #port -> Monitor web ui (Please disabled or keep secured)
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  service1:
    build: ./services1
    labels:
      - "traefik.http.routers.service1.rule=Host(`robohox.com`) || ( Host(`robohox.com`) && PathPrefix(`/s1`) )"
  service2:
    build: ./services2
    labels:
      - "traefik.http.routers.service2.rule=Host(`s2.robohox.com`) || ( Host(`robohox.com`) && PathPrefix(`/s2`) )"
